### ISSUE TITLE
Problem in building and linking C++ sources

### ISSUE THREAD

**Issue by richardclli** [CommunityGD32Cores/gd32-pio-spl-package#7] opened 2021-09-16 03:27 UTC
There are 2 problems in the libraries:

1. Some extern definition wrongly used #ifdef cplusplus, should use #ifdef __cpluscplus instead.
2. The bool definition will cause duplicate definition with c++ sources

I will work out a pull request with these all fixed, please review and approve afterwards.

**Comment by maxgerhardt** [comment] 2021-09-16 07:43
There must be third part to it: Call into global C++ constructors in the startup file. Our startup files currently do

https://github.com/CommunityGD32Cores/gd32-pio-spl-package/blob/68e40a2918a712dc62d32140aa5119343cfd1af8/gd32/cmsis/startup_files/startup_gd32f30x_hd.S#L55-L60

but other C++ frameworks like Arduino-STM32 [do this](https://github.com/stm32duino/Arduino_Core_STM32/blob/6dec3b655fda17ba0f33cf12cef16b64d0333abd/system/Drivers/CMSIS/Device/ST/STM32F0xx/Source/Templates/gcc/startup_stm32f030x6.s#L86-L91)

```asm
/* Call the clock system intitialization function.*/
  bl  SystemInit
/* Call static constructors */
  bl __libc_init_array
/* Call the application's entry point.*/
  bl main
```

The question is, can we write that in the startup file in all cases, even when C++ is not linked.

Have you got a full SPL + C++ example to test? With static constructors and calls into the standard lib?

**Comment by maxgerhardt** [comment] 2021-09-16 07:49
(Re-Opening because I don't think the issue is fully solved)

**Comment by richardclli** [comment] 2021-09-17 02:10
The same way for GD32VF103 series, the firmware library has these kind of bugs as well.  The problem solved by me is just the problem of linking with mixed C and C++ since C++ will have a different naming tags generation during preprocessing.  And need to declare extern C to make it work properly.

So to test it out, you can try to grab any example and rename the main.c to main.cpp and the build will failed without this patch.

**Comment by richardclli** [comment] 2021-09-17 02:14
Thanks for merging anyway, I have help to fix the GD32VF103 firmware as well, but nobody handles any pull request.

https://github.com/riscv-mcu/GD32VF103_Firmware_Library

**Comment by maxgerhardt** [comment] 2021-09-17 06:25
>Thanks for merging anyway, I have help to fix the GD32VF103 firmware as well, but nobody handles any pull request.

I think that's because the repo isn't the GigaDevice repo, but someone who just archived their original SPL package.

Thje GigaDevice company has a Github presence at https://github.com/GigaDevice-Semiconductor/, so you'll probably want to PR into https://github.com/GigaDevice-Semiconductor/GD32VF103_Firmware_Library. That is one of the only SPL package repos they have (none for the ARM chips). But I do have the impression they don't have a too strong presence on Github, issues like `https://github.com/GigaDevice-Semiconductor/openocd/issues/5` weren't yet e.g. commented on.

**Comment by maxgerhardt** [comment] 2021-09-17 06:26
>So to test it out, you can try to grab any example and rename the main.c to main.cpp and the build will failed without this patch.

Will do that along with testing static constructors + calls into C++ standard library + new examples. SPL and C++ is an intersting combination.

**Comment by maxgerhardt** [comment] 2021-09-21 11:18
Startup file for constructors fixed in https://github.com/CommunityGD32Cores/gd32-pio-spl-package/commit/691b94f8743406fc3b98d09f1a3b825799bc8f53, new project using C++ with SPL added in https://github.com/CommunityGD32Cores/gd32-pio-projects/tree/main/gd32-spl-blinky-with-c%2B%2B, compiled + tested on HW, runs fine.

**Closed as completed by maxgerhardt** 2021-09-21 11:18 UTC
